### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by xwjBupt** [lizhaode/91Crawer#1]
在国外的VPS上跑的，刚开始一直解析，然后就报错了，如下：

`
Traceback (most recent call last):
  File "main.py", line 93, in <module>
    use_map()
  File "main.py", line 85, in use_map
    p.map(download, video_name_and_url_dict.items())
  File "/root/anaconda3/lib/python3.7/multiprocessing/pool.py", line 290, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/root/anaconda3/lib/python3.7/multiprocessing/pool.py", line 683, in get
    raise self._value
  File "/root/anaconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/root/anaconda3/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "main.py", line 66, in download
    real_url_or_html = craw.parse_video_real_link(name_and_url[1])
  File "/root/NN/91Crawer/lib/CrawerImpl.py", line 59, in parse_video_real_link
    real_link = bs.find('video').find('source')['src']
TypeError: 'NoneType' object is not subscriptable
`

请问如何解决？

**Comment by xwjBupt** [comment]
python3.7

**Comment by lizhaode** [comment]
换成 scrapy 的那个吧，因为91为了防爬改成动态加载视频的地址了，这个脚本没更新，用不了

**Comment by lizhaode** [comment]
https://github.com/lizhaode/Scrapy91
